apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: flaskdemo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: ./
    repoURL: "https://github.com/aadilraza339/python-flask-deployment.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

